# Generated by Django 3.1 on 2021-05-09 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, default='', null=True)),
                ('designation', models.TextField(blank=True, default='', null=True)),
                ('from_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('to_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
