# Generated by Django 3.1 on 2021-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
