# Generated by Django 3.1 on 2021-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
