# Generated by Django 3.1 on 2021-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
