# Generated by Django 3.1 on 2021-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_education_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
