# Generated by Django 3.1 on 2021-05-09 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210509_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('from_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('to_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('is_present', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
