# Generated by Django 3.1 on 2021-06-18 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_achievements_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
